# Generated by Django 2.2.13 on 2021-07-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='modo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
