# Generated by Django 2.2.13 on 2021-08-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_url_modo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='modo',
            field=models.TextField(choices=[('business', 'Business'), ('social', 'Social')], default='business'),
        ),
    ]
