# Generated by Django 2.2.13 on 2021-08-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20210814_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='url',
            name='modo',
            field=models.CharField(choices=[('business', 'Business'), ('social', 'Social')], default='business', max_length=50),
        ),
    ]
