# Generated by Django 2.2.13 on 2021-09-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_auto_20210825_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='modo',
            field=models.CharField(choices=[('business', 'Business'), ('social', 'Social'), ('otro', 'Otro')], default='business', max_length=50),
        ),
        migrations.AlterField(
            model_name='url',
            name='modo',
            field=models.CharField(choices=[('business', 'Business'), ('social', 'Social'), ('otro', 'Otro')], default='business', max_length=50),
        ),
    ]
