# Generated by Django 2.2.13 on 2021-09-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_auto_20210903_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='colorBoton',
            field=models.CharField(choices=[('fucsia', 'fucsia'), ('blanco', 'blanco'), ('negro', 'negro'), ('rojo', 'rojo'), ('azul', 'azul'), ('verde', 'verde'), ('amarillo', 'amarillo'), ('naranja', 'naranja'), ('gris', 'gris'), ('violeta', 'violeta')], default='negro', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='colorFondo',
            field=models.CharField(choices=[('fucsia', 'fucsia'), ('blanco', 'blanco'), ('negro', 'negro'), ('rojo', 'rojo'), ('azul', 'azul'), ('verde', 'verde'), ('amarillo', 'amarillo'), ('naranja', 'naranja'), ('gris', 'gris'), ('violeta', 'violeta')], default='negro', max_length=50),
        ),
    ]
