# Generated by Django 2.2.13 on 2021-09-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_auto_20210903_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='modo',
            field=models.CharField(choices=[('Business', 'Business'), ('Social', 'Social'), ('Otro', 'Otro')], default='Business', max_length=50),
        ),
        migrations.AlterField(
            model_name='url',
            name='modo',
            field=models.CharField(choices=[('Business', 'Business'), ('Social', 'Social'), ('Otro', 'Otro')], default='business', max_length=50),
        ),
    ]
