# Generated by Django 2.2.13 on 2021-09-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_auto_20210903_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='portada',
            field=models.ImageField(default='portada.jpg', upload_to='photos'),
        ),
    ]
