# Generated by Django 3.2.7 on 2021-09-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_profile_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='archivo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
