# Generated by Django 3.2.7 on 2021-10-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_alter_url_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='url',
            name='modo',
            field=models.CharField(blank=True, choices=[('Business', 'Business'), ('Social', 'Social'), ('Otro', 'Otro')], default='business', max_length=50, null=True),
        ),
    ]
