# Generated by Django 3.2.7 on 2021-10-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_auto_20211002_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='company',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='location',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='mail',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='phone',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='website',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
